### PR TITLE
Add a label of Umbrella Roaming Client

### PR DESCRIPTION
**Pull request by kenchan0130**
This is a Roaming client mainly used by Cisico Umbrella.

https://support.umbrella.com/hc/en-us/articles/231356108-Roaming-Client-Deployment-Parameters-for-Mass-Deployment-MSP-

### CODE REVIEW

**Comment by scriptingosx** [comment]
I have made the label work, but the downloaded pkg fails with an error on macOS Catalina 10.15.4. Since it also fails when I install the pkg manually, I believe this is an issue of the pkg. Nothing we can do about it.

I'll keep this open until there is a solution.

**Comment by kenchan0130** [comment]
I can't check it immediately because my environment is mojave.
If you can, is it possible to get the log by executing the following command?

```sh
/usr/sbin/installer -dumplog -verbose -pkg "/path/to/packagefile" -target /
```

**Comment by scriptingosx** [comment]
```
% sudo installer -pkg /Users/armin/OneDrive\ -\ Pro\ Warehouse/Desktop/RoamingClient_MAC_2.1.40.pkg -tgt / -verboseR -dumplog
Password:
installer: Package name is Umbrella Roaming Client
May 18 14:11:09  installer[6333] <Debug>: Product archive /Users/armin/OneDrive - Pro Warehouse/Desktop/RoamingClient_MAC_2.1.40.pkg trustLevel=350
May 18 14:11:09  installer[6333] <Debug>: External component packages (1) trustLevel=350
installer: Installing at base path /
installer:PHASE:Preparing for installation…
May 18 14:11:09  installer[6333] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
May 18 14:11:09  installer[6333] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/armin/OneDrive%20-%20Pro%20Warehouse/Desktop/RoamingClient_MAC_2.1.40.pkg#Roaming_Client.pkg
May 18 14:11:09  installer[6333] <Debug>: Set authorization level to root for session
May 18 14:11:09  installer[6333] <Info>: Administrator authorization granted.
May 18 14:11:09  installer[6333] <Debug>: Will use PK session
May 18 14:11:09  installer[6333] <Debug>: Using authorization level of root for IFPKInstallElement
May 18 14:11:10  installer[6333] <Info>: Starting installation:
installer:PHASE:Preparing the disk…
May 18 14:11:10  installer[6333] <Notice>: Configuring volume "Macintosh HD"
May 18 14:11:10  installer[6333] <Info>: Preparing disk for local booted install.
May 18 14:11:10  installer[6333] <Notice>: Free space on "Macintosh HD": 23.55 GB (23548252160 bytes).
May 18 14:11:10  installer[6333] <Notice>: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.6333cG4gU7"
May 18 14:11:10  installer[6333] <Notice>: IFPKInstallElement (1 packages)
installer:PHASE:Preparing Umbrella Roaming Client…
installer:PHASE:Waiting for other installations to complete…
May 18 14:11:10  installer[6333] <Notice>: PackageKit: Enqueuing install with framework-specified quality of service (utility)
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%35.263630
installer:PHASE:Running package scripts…
installer:%37.144719
installer:PHASE:Running package scripts…
installer:%37.971099
installer:PHASE:Running package scripts…
installer:%82.944759
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
May 18 14:11:12  installer[6333] <Debug>: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “RoamingClient_MAC_2.1.40.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/armin/OneDrive%20-%20Pro%20Warehouse/Desktop/RoamingClient_MAC_2.1.40.pkg#Roaming_Client.pkg, PKInstallPackageIdentifier=com.opendns.osx.RoamingClient, NSLocalizedDescription=An error occurred while running scripts from the package “RoamingClient_MAC_2.1.40.pkg”.}
```

**Comment by kenchan0130** [comment]
Thank you for your confirmation.

The cause is that the downloaded pkg was not the latest version. It seems that the latest version cannot be obtained from the URL I have specified.
I'll investigate if I can get the latest version by any means.

**Comment by kenchan0130** [comment]
@scriptingosx 
Changed to a URL where the latest version can be obtained.

**Comment by scriptingosx** [comment]
merged into dev 594db2c6d60537228aa97c9764251661b9c754a5

**Pull request closed without merging**
