### PR TITLE
Improved 'pycharmce' for Apple Silicon

### PR DESCRIPTION
**Pull request by midni9ht**
Improved 'pycharmce' to make it distinguish between Intel and Apple Silicon architectures.
Added 'appNewVersion' to check for latest version.

### CODE REVIEW

**Comment by Theile** [comment]
Didn't I include those? 
We definitely use differentiation for Arm and Intel when no Universal version is available.

**Comment by midni9ht** [comment]
`downloadURL` currently points to https://download.jetbrains.com/product?code=PCC&latest&distribution=mac, which just downloads the Intel package.

`if [[ $(arch) == i386 ]]; then
      downloadURL=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCC&latest=true&type=release" | grep -o "mac*.*.dmg" | cut -d '"' -f5)
    elif [[ $(arch) == arm64 ]]; then
      downloadURL=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCC&latest=true&type=release" | grep -o "macM1*.*.dmg" | cut -d '"' -f5)
    fi`
should do the trick.

I also added `appNewVersion=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCC&latest=true&type=release" | grep -o 'version*.*,' | cut -d '"' -f3)`
in my pull request :-)

**Comment by Theile** [comment]
Yes, and this is how it looks in the code:
```
jetbrainspycharm)
    # credit: Adrian Bühler (@midni9ht)
    name="PyCharm"
    type="dmg"
    appNewVersion=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCP&latest=true&type=release" | grep -o 'version*.*,' | cut -d '"' -f3)
    if [[ $(arch) == i386 ]]; then
        downloadURL=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCP&latest=true&type=release" | grep -o "mac*.*.dmg" | cut -d '"' -f5)
    elif [[ $(arch) == arm64 ]]; then
        downloadURL=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCP&latest=true&type=release" | grep -o "macM1*.*.dmg" | cut -d '"' -f5)
    fi
    appNewVersion=$(curl -fs "https://data.services.jetbrains.com/products/releases?code=PCP&latest=true&type=release" | grep -o 'version*.*,' | cut -d '"' -f3)
    expectedTeamID="2ZEFAR8TH3"
    ;;

```

**Comment by Theile** [comment]
Think you looked at jetbrainspycharmce…

**Comment by midni9ht** [comment]
I think there is a misunderstanding. The URLs I quoted actually are for PyCharm CE (have a look at the product code, it's **PCP** for PyCharm (Pro) and **PCC** for PyCharm CE). The rest appears to be identical.
I know this is is somewhat confusing.

**Comment by midni9ht** [comment]
I'll go ahead and create another pull request ;-)

**Pull request closed without merging**
