### PR TITLE
Add apps to Installomator.sh

### PR DESCRIPTION
**Pull request by drewdiver**
Added TaskPaper, calibre, Red Eye, Lucifer, Fantastical and LaunchBar

### CODE REVIEW

**Comment by Theile** [comment]
Except for taskpaper, I have appNewVersion here:

Calibre:
`appNewVersion=$( curl -fsIL "${downloadURL}" | grep -i "^location" | awk '{print $2}' | sed -E 's/.*\/[a-zA-Z]*-([0-9.]*)\..*/\1/g' )`

Redeye:
`appNewVersion=$( curl -fs "https://www.hexedbits.com/redeye/" | grep "Latest version" | sed -E 's/.*Latest version ([0-9.]*),.*/\1/g' )`

Lucifer:
`appNewVersion=$( curl -fs "https://www.hexedbits.com/lucifer/" | grep "Latest version" | sed -E 's/.*Latest version ([0-9.]*),.*/\1/g' )`

Fantastical:
`appNewVersion=$( curl -fsIL "${downloadURL}" | grep -i "^location" | awk '{print $2}' | sed -E 's/.*\/[a-zA-Z]*_([0-9.]*)\..*/\1/g' )`

LaunchBar:
`appNewVersion=$( echo ${downloadURL} | sed -E 's/.*\/[a-zA-Z]*-([0-9.]*)\..*/\1/g' )`

**Comment by Theile** [comment]
Fusion is not a pkg, it's a dmg with a proprietary app for installation. It cannot work.

**Comment by drewdiver** [comment]
I just uncommented and ran on a fresh installed M1 MacBook Pro (11.1) and it worked, I'm currently setting up a VM as I type this.

**Comment by Theile** [comment]
But i just copied the app to Applications, then. And from there it got installed when you ran the app. No exactly a full installation, but if it was useful for you, that's great!

**Comment by Theile** [comment]
Thank you for all of these, they have been included in latest dev.

**Pull request closed without merging**
